### ISSUE TITLE
[FE] Mudar o FE para o novo formato de URL

### ISSUE THREAD

**Issue by danielfireman** [analytics-ufcg/cartao-fidelidade#28]
/fornecedores/:estado/:cpfcnpj/:legislatura/:type

**Comment by danielfireman** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HIFa3Pwe&#x2F;11-mudar-o-fe-para-o-novo-formato-de-url"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Mudar o FE para o novo formato de URL</a>

**Comment by marcuswac** [comment]
O front-end ainda está tentando acessar o formato antigo da API. Teria que rodar algo para re-gerar os .js e atualizar?

**Comment by danielfireman** [comment]
Eu mandei um pull request para Jeff corrigindo isso.

Em 26 de ago de 2016 09:33, "Marcus Carvalho" notifications@github.com
escreveu:
